apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: conversion-service
  name: conversion-service
spec:
  replicas: 3 #Difference
  selector:
    matchLabels:
      io.kompose.service: conversion-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: conversion-service
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka:8761/eureka/
            - name: eureka.instance.preferIPAddress
              value: "true"
          image: europe-west1-docker.pkg.dev/cloud-computing-cw-352806/cloud-repo/conversion_service  #Difference
          name: conversion-service
          ports:
            - containerPort: 2222
          resources: {}
      restartPolicy: Always
status: {}
